#!/bin/bash

DISK="/dev/sda"


printf "Overview of the drives:\n\n"
fdisk -l

# Update system clock
timedatectl set-ntp true


printf "Partitioning drives...\n"
# create partitioning table
parted -s "$DISK" mklabel msdos

# create root partition
parted -s "$DISK" mkpart primary 0% 15GB
parted -s "$DISK" set 1 boot on

# create home partition
parted -s "$DISK" mkpart primary 15GB 100%

# format drives
mkfs.ext4 -F "${DISK}1" 
mkfs.ext4 -F "${DISK}2"

# mount drives
printf "Mounting drives...\n"

mount "${DISK}1" /mnt
mkdir /mnt/home
mount "${DISK}2" /mnt/home
df

printf "Updating pacman...\n"
pacman -Syy

printf "Pacstrapping...\n"
pacstrap /mnt base base-devel grub openssh sudo ntp wget vim zsh

printf "Generating fstab...\n"
genfstab -U /mnt >> /mnt/etc/fstab

cp ./chroot.sh /mnt
cp ~/.ssh/authorized_keys /mnt
arch-chroot /mnt ./chroot.sh "$DISK"
rm /mnt/chroot.sh

umount -R /mnt/home
umount -R /mnt
systemctl reboot