#!/bin/bash
printf "Overview of the drives:\n\n"
fdisk -l

printf "Please specify the main disk for bootloader purposes: (i.e. sda, sdb) "
read DISK
DISK="/dev/$DISK"

printf "Please specify the partition for the root install: "
read ROOTPART

printf "Please specify the partition for the /home install: "
read HOMEPART

# partitioning of the drives
printf "Partitioning drives...\n"
parted -s "$DISK" mklabel msdos
parted -s -a optimal "$DISK" mkpart primary ext4 512B 15GB
parted -s "$DISK" set 1 boot on
parted -s -a optimal "$DISK" mkpart primary ext4 15GB 100%
mkfs.ext4 -F "$ROOTPART"
mkfs.ext4 -F "$HOMEPART"

# mount drives
printf "Mounting drives...\n"
mount "$ROOTPART" /mnt
mount "$HOMEPART" /mnt/home

printf "Updating pacman...\n"
pacman -Syy

printf "Pacstrapping...\n"
pacstrap /mnt base base-devel grub ntp openssh sudo wget vim zsh

printf "Generating fstab...\n"
genfstab -U /mnt >> /mnt/etc/fstab

printf "Entering chroot...\n"
chmod +x chroot
cp ./chroot /mnt
arch-chroot /mnt ./chroot "$DISK"

#umount -R /mnt/home
#umount -R /mnt
#systemctl reboot